config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :testimonial_slides
  resources :testimonials, param: :slug
  resources :works_withs, param: :slug
  resources :example_images
  resources :products
  resources :use_cases, param: :slug
  resources :app_store_links
  resources :app_stores
  resources :apps, param: :slug
  resources :partners, param: :slug
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get 'home' => 'home#index'
  get 'cookie-policy' => 'cookie_policy#index'
  get 'cookies' => 'cookie_policy#index'
  get 'style-guide', :to => redirect('/assets/styleguide.html')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    ##
    # Creates arrays of Testimonials and Works With
    # for use with promotional components on the homepage
    add_breadcrumb 'Home', home_path
    @testimonial_promos = Testimonial.all.last(3)
    @featured_example = WorksWith.all.last(1)
    @page_title = t('pages.homepage.meta.title')
    @page_description = t('pages.homepage.meta.description')
    @page_keywords = t('pages.homepage.meta.keywords')
  end
end

app/views/home/index.html.haml
.home
  .introduction
    .introduction-columns
      %h1.introduction-title
        Works With
      .introduction-column
        %p
          Our Works With program is all about boosting efficiency, productivity and creativity – in the office, studio, lecture hall and on the move. Works With is a network of digital partners whose apps and software talk directly to the Moleskine+ Smart Writing System, so that your handwritten notes and hand-drawn sketches can immediately take on new life via the relevant digital platform.
      .introduction-column
        %p
          We recognize that ideas flow more naturally from the tip of a pen, while the digital sphere offers the quickest and easiest way of expanding and sharing them. The Smart Writing System bridges both analog and digital to bring you the best of both worlds at once. Works With finds smart solutions for your creative tasks, team work projects, academic assignments and professional activities. Simply choose the right Paper Tablet or Smart Cahier for you, grab your Pen+ smart pen, identify which digital platform fits your needs, and start expressing yourself!
  -@featured_example.each do |x|
    .feature{:onclick =>"location.href='#{works_with_path(x.slug)}'"}
      %img.lazyload{:data=>{:srcset=> get_src_set(x.promo_image_url, [1920,768,992]),:sizes=>'auto', :parent=> {:fit=>'cover'}}}
      .rounded-corner
        %h3
          = x.title